package main

// Language support
type Language string

const (
	LangEnglish Language = "en"
	LangGerman  Language = "de"
	LangSwahili Language = "sw"
)

var currentLanguage = LangEnglish

// Localization texts
var texts = map[Language]map[string]string{
	LangEnglish: {
		"title":                   "🎵 Multi-Room Audio Controller",
		"scanning":                "🔍 Scanning network for audio players...",
		"scanning_network":        "   Scanning network: %s",
		"scanning_interface":      "   Interface %s: %s",
		"found_player":            "   ✅ Found: %s (%s) at %s",
		"no_players":              "no audio players found",
		"could_not_determine_ip":  "could not determine local IP: %w",
		"available_players":       "📱 Available Players:",
		"select_player":           "Select a player (1-%d): ",
		"invalid_selection":       "❌ Invalid selection",
		"connected_to":            "✅ Connected to: %s (%s)",
		"error_selecting_player":  "Error selecting player: %v",
		"interactive_mode":        "🎵 Multi-Room Audio Controller - Interactive Mode",
		"separator":               "=======================================",
		"status_volume":           "📊 Status: %s | Volume: %s",
		"volume_unknown":          "N/A",
		"error_retrieving_status": "❌ Error retrieving status",
		"available_presets":       "📋 Available Presets/Favorites:",
		"error_loading_presets":   "❌ Error loading presets/favorites",
		"category_station":        "📻 Stations:",
		"category_playlist":       "📃 Playlists:",
		"category_album":          "💿 Albums:",
		"category_song":           "🎵 Songs:",
		"presets_page":            "-- Page %d/%d (n = next, p = previous) --",
		"available_commands":      "🎮 Available Commands:",
		"cmd_play_preset":         "play <id>   - Play preset/favorite",
		"cmd_play":                "play       - Start playback",
		"cmd_pause":               "pause      - Pause playback",
		"cmd_stop":                "stop       - Stop playback",
		"cmd_next":                "next       - Next track",
		"cmd_prev":                "prev       - Previous track",
		"cmd_volume":              "vol <0-100> - Set volume",
		"cmd_status":              "status     - Refresh status",
		"cmd_presets":             "presets    - Refresh presets/favorites",
		"cmd_help":                "help       - Show help",
		"cmd_lang":                "lang <en|de|sw> - Change language",
		"cmd_output":              "output <id> - Switch to player",
		"cmd_group":               "group <id1+id2> - Group players",
		"cmd_ungroup":             "ungroup - Remove all groups",
		"cmd_debug":               "debug - Show API endpoints",
		"cmd_quit":                "quit/exit  - Exit program",
		"prompt":                  "Command> ",
		"invalid_preset_id":       "❌ Invalid preset/favorite ID",
		"error_playing_preset":    "❌ Error playing preset/favorite",
		"playing_preset":          "✅ Playing preset/favorite %d",
		"error_starting_playback": "❌ Error starting playback",
		"playback_started":        "▶️ Playback started",
		"error_pausing":           "❌ Error pausing",
		"paused":                  "⏸️ Paused",
		"error_stopping":          "❌ Error stopping",
		"stopped":                 "⏹️ Stopped",
		"error_next_track":        "❌ Error skipping to next track",
		"next_track":              "⏭️ Next track",
		"error_prev_track":        "❌ Error going to previous track",
		"prev_track":              "⏮️ Previous track",
		"volume_missing":          "❌ Volume value missing",
		"invalid_volume":          "❌ Invalid volume value",
		"error_setting_volume":    "❌ Error setting volume",
		"volume_set":              "🔊 Volume set to %d%%",
		"language_changed":        "🌍 Language changed to",
		"invalid_language":        "❌ Invalid language. Use: en, de, sw",
		"goodbye":                 "👋 Goodbye!",
		"unknown_command":         "❌ Unknown command: %s (Type 'help' for help)",
		"last_action":             "Last Action:",
		"no_song_playing":         "No song playing",
		"available_outputs":       "📱 Available Players:",
		"current_player":          "Current Player:",
		"switched_to_player":      "🔄 Switched to player %d: %s",
		"invalid_player_id":       "❌ Invalid player ID",
		"error_switching_player":  "❌ Error switching to player",
		"grouped_players":         "🔗 Grouped players: %s as master",
		"invalid_group_format":    "❌ Invalid group format. Use: group <id1+id2>",
		"error_grouping":          "❌ Error grouping players",
		"group_combinations":      "🎵 Group Combinations:",
		"no_group_combinations":   "No compatible players to group (need 2+ players of the same type).",
		"ungrouped_all":           "🔓 All player groups removed",
		"error_ungrouping":        "❌ Error removing groups",
		"scanning_interfaces":     "🔍 Found %d network interfaces to scan",
		"completed_scan":          "✅ Completed scanning %d networks",
	},
	LangGerman: {
		"title":                   "🎵 Multi-Room Audio Controller",
		"scanning":                "🔍 Suche nach Audio-Playern im Netzwerk...",
		"scanning_network":        "   Scanne Netzwerk: %s",
		"scanning_interface":      "   Interface %s: %s",
		"found_player":            "   ✅ Gefunden: %s (%s) auf %s",
		"no_players":              "keine Audio-Player gefunden",
		"could_not_determine_ip":  "konnte lokale IP nicht ermitteln: %w",
		"available_players":       "📱 Verfügbare Player:",
		"select_player":           "Wähle einen Player (1-%d): ",
		"invalid_selection":       "❌ Ungültige Auswahl",
		"connected_to":            "✅ Verbunden mit: %s (%s)",
		"error_selecting_player":  "Fehler bei der Player-Auswahl: %v",
		"interactive_mode":        "🎵 Multi-Room Audio Controller - Interaktiver Modus",
		"separator":               "==========================================",
		"status_volume":           "📊 Status: %s | Lautstärke: %s",
		"volume_unknown":          "N/A",
		"error_retrieving_status": "❌ Fehler beim Abrufen des Status",
		"available_presets":       "📋 Verfügbare Presets/Favoriten:",
		"error_loading_presets":   "❌ Fehler beim Laden der Presets/Favoriten",
		"category_station":        "📻 Sender:",
		"category_playlist":       "📃 Playlists:",
		"category_album":          "💿 Alben:",
		"category_song":           "🎵 Songs:",
		"presets_page":            "-- Seite %d/%d (n = weiter, p = zurück) --",
		"available_commands":      "🎮 Verfügbare Befehle:",
		"cmd_play_preset":         "play <id>   - Preset/Favorit abspielen",
		"cmd_play":                "play       - Wiedergabe starten",
		"cmd_pause":               "pause      - Pausieren",
		"cmd_stop":                "stop       - Stoppen",
		"cmd_next":                "next       - Nächster Titel",
		"cmd_prev":                "prev       - Vorheriger Titel",
		"cmd_volume":              "vol <0-100> - Lautstärke setzen",
		"cmd_status":              "status     - Status aktualisieren",
		"cmd_presets":             "presets    - Presets/Favoriten aktualisieren",
		"cmd_help":                "help       - Hilfe anzeigen",
		"cmd_lang":                "lang <en|de|sw> - Sprache ändern",
		"cmd_output":              "output <id> - Zu Player wechseln",
		"cmd_group":               "group <id1+id2> - Player gruppieren",
		"cmd_ungroup":             "ungroup - Alle Gruppen auflösen",
		"cmd_debug":               "debug - API-Endpunkte anzeigen",
		"cmd_quit":                "quit/exit  - Programm beenden",
		"prompt":                  "Befehl> ",
		"invalid_preset_id":       "❌ Ungültige Preset/Favoriten-ID",
		"error_playing_preset":    "❌ Fehler beim Abspielen",
		"playing_preset":          "✅ Preset/Favorit %d wird abgespielt",
		"error_starting_playback": "❌ Fehler beim Starten",
		"playback_started":        "▶️ Wiedergabe gestartet",
		"error_pausing":           "❌ Fehler beim Pausieren",
		"paused":                  "⏸️ Pausiert",
		"error_stopping":          "❌ Fehler beim Stoppen",
		"stopped":                 "⏹️ Gestoppt",
		"error_next_track":        "❌ Fehler beim Weiterschalten",
		"next_track":              "⏭️ Nächster Titel",
		"error_prev_track":        "❌ Fehler beim Zurückschalten",
		"prev_track":              "⏮️ Vorheriger Titel",
		"volume_missing":          "❌ Lautstärke-Wert fehlt",
		"invalid_volume":          "❌ Ungültiger Lautstärke-Wert",
		"error_setting_volume":    "❌ Fehler beim Setzen der Lautstärke",
		"volume_set":              "🔊 Lautstärke auf %d%% gesetzt",
		"language_changed":        "🌍 Sprache geändert zu",
		"invalid_language":        "❌ Ungültige Sprache. Verwende: en, de, sw",
		"goodbye":                 "👋 Auf Wiedersehen!",
		"unknown_command":         "❌ Unbekannter Befehl: %s (Tippe 'help' für Hilfe)",
		"last_action":             "Letzte Aktion:",
		"no_song_playing":         "Kein Lied wird abgespielt",
		"available_outputs":       "📱 Verfügbare Player:",
		"current_player":          "Aktueller Player:",
		"switched_to_player":      "🔄 Gewechselt zu Player %d: %s",
		"invalid_player_id":       "❌ Ungültige Player-ID",
		"error_switching_player":  "❌ Fehler beim Wechseln des Players",
		"grouped_players":         "🔗 Player gruppiert: %s als Master",
		"invalid_group_format":    "❌ Ungültiges Gruppen-Format. Verwende: group <id1+id2>",
		"error_grouping":          "❌ Fehler beim Gruppieren",
		"group_combinations":      "🎵 Gruppen-Kombinationen:",
		"no_group_combinations":   "Keine kompatiblen Player zum Gruppieren (mind. 2 Player desselben Typs nötig).",
		"ungrouped_all":           "🔓 Alle Player-Gruppen aufgelöst",
		"error_ungrouping":        "❌ Fehler beim Auflösen der Gruppen",
		"scanning_interfaces":     "🔍 %d Netzwerkschnittstellen gefunden zum Scannen",
		"completed_scan":          "✅ Scannen von %d Netzwerken abgeschlossen",
	},
	LangSwahili: {
		"title":                   "🎵 Kidhibiti cha Audio ya Multi-Room",
		"scanning":                "🔍 Kutafuta vichezaji vya audio kwenye mtandao...",
		"scanning_network":        "   Kutafuta mtandao: %s",
		"scanning_interface":      "   Interface %s: %s",
		"found_player":            "   ✅ Kumepatikana: %s (%s) kwa %s",
		"no_players":              "hakuna vichezaji vya audio vilivopatikana",
		"could_not_determine_ip":  "haikuweza kutambua IP ya ndani: %w",
		"available_players":       "📱 Vichezaji Vinavyopatikana:",
		"select_player":           "Chagua kichezaji (1-%d): ",
		"invalid_selection":       "❌ Chaguo batili",
		"connected_to":            "✅ Imeunganishwa na: %s (%s)",
		"error_selecting_player":  "Hitilafu katika kuchagua kichezaji: %v",
		"interactive_mode":        "🎵 Kidhibiti cha Audio ya Multi-Room - Hali ya Maingiliano",
		"separator":               "===========================================",
		"status_volume":           "📊 Hali: %s | Sauti: %s",
		"volume_unknown":          "N/A",
		"error_retrieving_status": "❌ Hitilafu katika kupata hali",
		"available_presets":       "📋 Mipangilio/Vipendwa Vinavyopatikana:",
		"error_loading_presets":   "❌ Hitilafu katika kupakia mipangilio/vipendwa",
		"category_station":        "📻 Vituo:",
		"category_playlist":       "📃 Orodha za Nyimbo:",
		"category_album":          "💿 Albamu:",
		"category_song":           "🎵 Nyimbo:",
		"presets_page":            "-- Ukurasa %d/%d (n = mbele, p = nyuma) --",
		"available_commands":      "🎮 Amri Zinazopatikana:",
		"cmd_play_preset":         "play <id>   - Cheza mpangilio/kipendwa",
		"cmd_play":                "play       - Anza kucheza",
		"cmd_pause":               "pause      - Simamisha",
		"cmd_stop":                "stop       - Acha",
		"cmd_next":                "next       - Wimbo ujao",
		"cmd_prev":                "prev       - Wimbo uliopita",
		"cmd_volume":              "vol <0-100> - Weka sauti",
		"cmd_status":              "status     - Onyesha hali",
		"cmd_presets":             "presets    - Onyesha mipangilio/vipendwa",
		"cmd_help":                "help       - Onyesha msaada",
		"cmd_lang":                "lang <en|de|sw> - Badilisha lugha",
		"cmd_output":              "output <id> - Badili kichezaji",
		"cmd_group":               "group <id1+id2> - Unganisha vichezaji",
		"cmd_ungroup":             "ungroup - Ondoa vikundi vyote",
		"cmd_debug":               "debug - Onyesha API endpoints",
		"cmd_quit":                "quit/exit  - Toka programu",
		"prompt":                  "Amri> ",
		"invalid_preset_id":       "❌ Kitambulisho cha mpangilio/kipendwa si halali",
		"error_playing_preset":    "❌ Hitilafu katika kucheza mpangilio/kipendwa",
		"playing_preset":          "✅ Kucheza mpangilio/kipendwa %d",
		"error_starting_playback": "❌ Hitilafu katika kuanza kucheza",
		"playback_started":        "▶️ Imeanza kucheza",
		"error_pausing":           "❌ Hitilafu katika kusimamisha",
		"paused":                  "⏸️ Imesimamishwa",
		"error_stopping":          "❌ Hitilafu katika kuacha",
		"stopped":                 "⏹️ Imeachwa",
		"error_next_track":        "❌ Hitilafu katika kuruka wimbo ujao",
		"next_track":              "⏭️ Wimbo ujao",
		"error_prev_track":        "❌ Hitilafu katika kurudi wimbo uliopita",
		"prev_track":              "⏮️ Wimbo uliopita",
		"volume_missing":          "❌ Thamani ya sauti inakosekana",
		"invalid_volume":          "❌ Thamani ya sauti si halali",
		"error_setting_volume":    "❌ Hitilafu katika kuweka sauti",
		"volume_set":              "🔊 Sauti imewekwa %d%%",
		"language_changed":        "🌍 Lugha imebadilishwa kuwa",
		"invalid_language":        "❌ Lugha si halali. Tumia: en, de, sw",
		"goodbye":                 "👋 Kwaheri!",
		"unknown_command":         "❌ Amri isiyojulikana: %s (Andika 'help' kwa msaada)",
		"last_action":             "Kitendo cha Mwisho:",
		"no_song_playing":         "Hakuna wimbo unaochezwa",
		"available_outputs":       "📱 Vichezaji Vinavyopatikana:",
		"current_player":          "Kichezaji cha Sasa:",
		"switched_to_player":      "🔄 Imebadilishwa kwa kichezaji %d: %s",
		"invalid_player_id":       "❌ Kitambulisho cha kichezaji si halali",
		"error_switching_player":  "❌ Hitilafu katika kubadili kichezaji",
		"grouped_players":         "🔗 Vichezaji vimeunganishwa: %s kama mkuu",
		"invalid_group_format":    "❌ Muundo wa kikundi si halali. Tumia: group <id1+id2>",
		"error_grouping":          "❌ Hitilafu katika kuunganisha",
		"group_combinations":      "🎵 Miunganiko ya Vikundi:",
		"no_group_combinations":   "Hakuna vichezaji vinavyolingana kuunganishwa (vinahitajika vichezaji 2+ vya aina moja).",
		"ungrouped_all":           "🔓 Vikundi vyote vya vichezaji vimeondolewa",
		"error_ungrouping":        "❌ Hitilafu katika kuondoa vikundi",
		"scanning_interfaces":     "🔍 Kumepatikana %d network interfaces za kutafuta",
		"completed_scan":          "✅ Imemaliza kutafuta %d mitandao",
	},
}

// Helper function to get localized text
func getText(key string) string {
	if text, exists := texts[currentLanguage][key]; exists {
		return text
	}
	// Fallback to English if key not found
	if text, exists := texts[LangEnglish][key]; exists {
		return text
	}
	return key // Return key as fallback
}

// categoryLabel returns the localized, icon-prefixed header for a preset
// category, used by PrintPresetsGrouped.
func categoryLabel(cat PresetCategory) string {
	switch cat {
	case CategoryPlaylist:
		return getText("category_playlist")
	case CategoryAlbum:
		return getText("category_album")
	case CategorySong:
		return getText("category_song")
	default:
		return getText("category_station")
	}
}
